export let QuizBank = [
	{
		quiz_num: 1,
		quiz_name: 'math-addition',
		created_date: '2023-12-04',
		questions: [
			{
				question: '5 + 5 = ?',
				optionA: 8,
				optionB: 9,
				optionC: 10,
				optionD: 11,
				answer: 'C',
			},
			{
				question: '6 + 7 = ?',
				optionA: 11,
				optionB: 12,
				optionC: 13,
				optionD: 14,
				answer: 'C',
			},
			{
				question: '8 + 9 = ?',
				optionA: 16,
				optionB: 17,
				optionC: 18,
				optionD: 19,
				answer: 'B',
			},
		],
	},
	{
		quiz_num: 2,
		quiz_name: 'math-subtraction',
		created_date: '2023-12-05',
		questions: [
			{
				question: '5 - 5 = ?',
				optionA: 0,
				optionB: 1,
				optionC: 3,
				optionD: 5,
				answer: 'A',
			},
			{
				question: '9 - 6 = ?',
				optionA: 2,
				optionB: 3,
				optionC: 4,
				optionD: 5,
				answer: 'B',
			},
			{
				question: '8 - 2 = ?',
				optionA: 2,
				optionB: 4,
				optionC: 6,
				optionD: 8,
				answer: 'C',
			},
			{
				question: '7 - 4 = ?',
				optionA: 2,
				optionB: 3,
				optionC: 4,
				optionD: 5,
				answer: 'B',
			},
		],
	},
];
